"""
Django settings for main_site project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.core.management.utils import get_random_secret_key
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key())

# Determine if running in production or development
IS_PRODUCTION = os.environ.get('ENVIRONMENT') == 'production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# Allow hosts based on environment
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['.vercel.app']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# For Vercel serverless, keep cookies host-only (vercel.app is a public suffix)
if IS_PRODUCTION:
    SESSION_COOKIE_DOMAIN = None  # Host-only cookie required for Vercel
    CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']
    # Trust the X-Forwarded-Proto header from Vercel's proxy
    SECURE_PROXY_SSL_HEADER = ('X-Forwarded-Proto', 'https')


# Increase max upload size for cover photos (10 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'channels',
    'presenta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'presenta.middleware.UserActivityMiddleware',
]

ROOT_URLCONF = 'main_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'presenta.context_processors.user_profile',
                'presenta.context_processors.announcement_banner',
                'presenta.context_processors.user_notifications',
                'presenta.context_processors.user_currency',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
# Media files (user-uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends: try presenta backend first, then default model backend
AUTHENTICATION_BACKENDS = [
    'presenta.auth_backend.PresentaBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Default redirect after login (avoid Django's /accounts/profile/ default)
LOGIN_REDIRECT_URL = '/'

# Session settings for persistent login
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Session engine selection:
# - signed_cookies: Works on serverless (data encoded in cookie, no DB needed)
# - db (default): Requires persistent database connection (PostgreSQL recommended)
SESSION_ENGINE = os.environ.get('SESSION_ENGINE', 'django.contrib.sessions.backends.signed_cookies')

# Use JSON serializer for better compatibility with signed cookies
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Cookie settings for production (Vercel requires secure cookies)
SESSION_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = IS_PRODUCTION

# Ensure session cookie works on Vercel (host-only)
if IS_PRODUCTION:
    SESSION_COOKIE_DOMAIN = None
    CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']
    SECURE_PROXY_SSL_HEADER = ('X-Forwarded-Proto', 'https')
    SECURE_SSL_REDIRECT = True

# ASGI/Channels configuration
ASGI_APPLICATION = 'main_site.asgi.application'

# Channel layers for WebSocket support
CHANNEL_LAYERS = {
    'BACKEND': 'channels.layers.InMemoryChannelLayer',
}
