# Generated by Django 4.2.11 on 2026-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0008_alter_user_options_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('for_payment', 'For Payment'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
