# Generated by Django 4.2.11 on 2026-02-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0009_alter_designrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='design_type',
            field=models.CharField(choices=[('presentation', 'Presentation'), ('infographic', 'Infographic'), ('poster', 'Poster')], default='presentation', max_length=20),
        ),
        migrations.CreateModel(
            name='DesignRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='design_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_files', to='presenta.designrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
