# Generated by Django 6.0.2 on 2026-02-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0010_designrequest_design_type_designrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequestfile',
            name='file_type',
            field=models.CharField(choices=[('reference', 'Reference File'), ('finished', 'Finished Design')], default='reference', max_length=20),
        ),
        migrations.AlterField(
            model_name='designrequestfile',
            name='design_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='presenta.designrequest'),
        ),
    ]
