# Generated by Django 6.0.2 on 2026-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0011_designrequestfile_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('for_payment', 'For Payment'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
