# Generated by Django 6.0.2 on 2026-02-24 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0012_alter_designrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('assigned', 'Designer Assigned'), ('completed', 'Completed'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('revision_requested', 'Revision Requested'), ('user_created', 'User Created'), ('request_rejected', 'Request Rejected'), ('request_cancelled', 'Request Cancelled')], max_length=30)),
                ('message', models.TextField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='presenta.designrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
