# Generated by Django 4.2.11 on 2026-02-26 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenta', '0013_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('assigned', 'Designer Assigned'), ('completed', 'Completed'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('revision_requested', 'Revision Requested'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('request_rejected', 'Request Rejected'), ('request_cancelled', 'Request Cancelled'), ('login', 'User Login'), ('logout', 'User Logout'), ('profile_updated', 'Profile Updated'), ('file_uploaded', 'File Uploaded'), ('password_changed', 'Password Changed')], max_length=30),
        ),
    ]
