# Generated by Django 4.2.11 on 2026-02-28 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenta', '0015_alter_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_preference', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('order_updates_email', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='immediate', max_length=20)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('designer_availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('designer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('designer_specializations', models.TextField(blank=True, help_text='Comma-separated list of specializations')),
                ('accept_project_requests', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
