# Generated by Django 4.2.11 on 2026-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0016_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='currency_preference',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('PHP', 'Philippine Peso (₱)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_concurrent_projects',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='minimum_project_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferred_design_types',
            field=models.TextField(blank=True, help_text='Comma-separated preferred design types'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='revision_limit',
            field=models.IntegerField(blank=True, default=3, help_text='Maximum revisions per project'),
        ),
    ]
