# Generated by Django 4.2.11 on 2026-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0017_usersettings_currency_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('PHP', 'Philippine Peso (₱)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='USD', max_length=10),
        ),
    ]
