# Generated by Django 4.2.11 on 2026-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0018_designrequest_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('do_not_disturb', 'Do Not Disturb')], default='online', max_length=20),
        ),
    ]
