# Generated by Django 4.2.11 on 2026-03-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0019_user_online_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='show_online_status',
            new_name='show_user_status',
        ),
    ]
