# Generated by Django 4.2.11 on 2026-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0020_rename_show_online_status_to_show_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, help_text='e.g., he/him, she/her, they/them', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='announcement_banner',
            field=models.TextField(blank=True, help_text='Site-wide announcement banner message'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='announcement_banner_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='api_rate_limit',
            field=models.IntegerField(default=100, help_text='API requests per hour limit'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_accept_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-accept projects matching criteria'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_refund_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='availability_hours',
            field=models.CharField(blank=True, choices=[('hours_9_5', '9 AM - 5 PM'), ('hours_8_6', '8 AM - 6 PM'), ('hours_10_8', '10 AM - 8 PM'), ('flexible', 'Flexible Hours'), ('custom', 'Custom Hours')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='backup_schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('inapp', 'In-App Messaging')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custom_hours',
            field=models.CharField(blank=True, help_text='Custom availability hours, e.g., "Mon-Fri 2PM-10PM"', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dispute_resolution_days',
            field=models.IntegerField(default=30, help_text='Days allowed for dispute resolution'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_template_notification',
            field=models.TextField(blank=True, help_text='Custom HTML for notification email'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_template_welcome',
            field=models.TextField(blank=True, help_text='Custom HTML for welcome email'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='extra_revision_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per extra revision', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='form_submission_limit',
            field=models.IntegerField(default=50, help_text='Form submissions per hour limit'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='grant_analytics_to_roles',
            field=models.TextField(blank=True, help_text='Comma-separated roles with analytics access: designer, admin'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='industry_expertise',
            field=models.TextField(blank=True, help_text='Comma-separated industries: Tech, Fashion, Real Estate, etc.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='moderation_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for content flagging'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Primary payment gateway: Stripe, PayPal, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='payout_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='payout_method',
            field=models.CharField(blank=True, help_text='Preferred payout method: bank transfer, PayPal, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='PayPal Client ID (encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='portfolio_public',
            field=models.BooleanField(default=True, help_text='Show portfolio to non-logged-in users'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('inapp', 'In-App Messaging')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='rush_job_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.25, help_text='Multiplier for rush jobs (e.g., 1.25 = 25% extra)', max_digits=3),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seasonal_active',
            field=models.BooleanField(default=False, help_text='Enable seasonal settings'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seasonal_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seasonal_fee_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Fee multiplier during peak season', max_digits=3),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seasonal_name',
            field=models.CharField(blank=True, help_text='e.g., Holiday Season, New Year', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='seasonal_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_testimonials',
            field=models.BooleanField(default=True, help_text='Display client testimonials on profile'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media URLs: {"linkedin": "", "twitter": "", "instagram": "", "portfolio": ""}'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='software_tools',
            field=models.TextField(blank=True, help_text='Design software proficiency: Figma, Adobe Suite, etc.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='stripe_api_key',
            field=models.CharField(blank=True, help_text='Stripe API Key (encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='turnaround_time_days',
            field=models.IntegerField(blank=True, default=5, help_text='Typical project turnaround time in days'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user_approval_required',
            field=models.BooleanField(default=False, help_text='Require admin approval for new user signups'),
        ),
    ]
