# Generated by Django 4.2.11 on 2026-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0021_user_email_verified_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='paypal_client_id',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='stripe_api_key',
        ),
    ]
