# Generated by Django 4.2.11 on 2026-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0022_remove_usersettings_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='announcement_banner_bg_color',
            field=models.CharField(blank=True, default='', help_text='Custom background color (e.g., #FF5733). Leave empty for default type color.', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='announcement_banner_text_color',
            field=models.CharField(blank=True, default='', help_text='Custom text color (e.g., #FFFFFF). Leave empty for default white text.', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='announcement_banner_type',
            field=models.CharField(choices=[('info', 'Info (Blue)'), ('warning', 'Warning (Orange)'), ('success', 'Success (Green)'), ('error', 'Error (Red)')], default='info', help_text='Type of announcement banner', max_length=20),
        ),
    ]
