# Generated by Django 4.2.11 on 2026-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0023_add_announcement_banner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_approval_status',
            field=models.CharField(choices=[('pending', 'Pending Owner Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
