# Generated by Django 5.2.11 on 2026-03-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0025_user_is_banned_alter_user_admin_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Presentations, Infographics, Posters)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text='Icon emoji or class name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on the samples page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sample Category',
                'verbose_name_plural': 'Sample Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the sample', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the sample')),
                ('image', models.ImageField(help_text='Sample image', upload_to='samples/')),
                ('client_name', models.CharField(blank=True, help_text='Client name (optional)', max_length=200)),
                ('project_date', models.DateField(blank=True, help_text='Date of the project', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('link', models.URLField(blank=True, help_text='External link to view more')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Show this sample on the samples page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this sample belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presenta.samplecategory')),
            ],
            options={
                'verbose_name': 'Sample Item',
                'verbose_name_plural': 'Sample Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
