# Generated by Django 5.2.11 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0026_samplecategory_sampleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='greeting_name_preference',
            field=models.CharField(choices=[('first_name', 'First Name Only'), ('full_name', 'Full Name')], default='first_name', help_text='Choose how your name appears in dashboard greetings', max_length=20),
        ),
    ]
