# Generated by Django 6.0.3 on 2026-03-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0027_alter_user_options_remove_profile_presenta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='design_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='presenta.designrequest'),
        ),
    ]
