# Generated by Django 5.2.11 on 2026-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0027_usersettings_greeting_name_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_time_date',
            field=models.BooleanField(default=True, help_text='Show time and date beside the greeting in dashboard'),
        ),
    ]
