# Generated by Django 5.2.11 on 2026-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0028_usersettings_show_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('request_submitted', 'Request Submitted'), ('status_changed', 'Status Changed'), ('assigned', 'Designer Assigned'), ('designer_assigned', 'Designer Assigned to Request'), ('completed', 'Completed'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('revision_requested', 'Revision Requested'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('request_rejected', 'Request Rejected'), ('request_cancelled', 'Request Cancelled'), ('file_uploaded', 'File Uploaded'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=30),
        ),
    ]
