# Generated by Django 6.0.2 on 2026-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0031_designerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Notes from client when requesting revision', null=True),
        ),
    ]
