# Generated by Django 5.2.11 on 2026-04-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0032_add_favorite_designer'),
        ('presenta', '0032_designrequest_revision_notes'),
    ]

    operations = [
    ]
