# Generated by Django 5.2.11 on 2026-04-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0033_merge_20260403_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_uid',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
