# Generated by Django 6.0.2 on 2026-04-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0033_chatmessage'),
        ('presenta', '0034_report_report_uid'),
    ]

    operations = [
    ]
