# Generated by Django 6.0.3 on 2026-04-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0037_chatmessage_attachment_chatmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='presenta_ch_receive_0698fd_idx',
            old_name='presenta_ch_receiver__d9164f_idx',
        ),
    ]
