# Generated by Django 6.0.3 on 2026-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0037_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('do_not_disturb', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
