# Generated by Django 6.0.3 on 2026-04-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0038_alter_user_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='presenta.chatmessage'),
        ),
    ]
