# Generated by Django 6.0.3 on 2026-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0039_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerrating',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional testimonial comment'),
        ),
    ]
