# Generated by Django 6.0.3 on 2026-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenta', '0041_add_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('payment_required', 'Payment Required'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
